spring.application:
    name: snowflake-metrics-exporter

spring.datasource:
    driverClassName: net.snowflake.client.jdbc.SnowflakeDriver
    maxActive: 1

management:
    endpoint.health:
        show-details: ALWAYS
        probes.enabled: true
    endpoints.web.exposure.include: "*"
    health.db.enabled: false
